### ISSUE TITLE
Crashes with battlegear 2 mod

### ISSUE THREAD

**Issue by Alexander175** [KuroNeko87/littleMaidMobX#13]
So I have a crash report to report about with little maids. So i have multiple mods installed but when i send a maid to attack with a bow or sword it crashes. I am thinking it is battlegear 2 that is causing this problem. Crash report below.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/14/15 9:00 PM
Description: Ticking entity

java.lang.ClassCastException: littleMaidMobX.LMM_InventoryLittleMaid cannot be cast to mods.battlegear2.api.core.InventoryPlayerBattle
	at mods.battlegear2.BowHookContainerClass2$OffhandQuiverSelection.getQuiverFor(BowHookContainerClass2.java:39)
	at mods.battlegear2.api.quiver.QuiverArrowRegistry.getArrowContainer(QuiverArrowRegistry.java:126)
	at mods.battlegear2.BowHookContainerClass2.onBowFiring(BowHookContainerClass2.java:118)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_BowHookContainerClass2_onBowFiring_ArrowLooseEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.item.ItemBow.func_77615_a(ItemBow.java:37)
	at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:402)
	at littleMaidMobX.LMM_SwingStatus.stopUsingItem(LMM_SwingStatus.java:170)
	at littleMaidMobX.LMM_EntityLittleMaidAvatar.stopUsingItem(LMM_EntityLittleMaidAvatar.java:283)
	at littleMaidMobX.LMM_EntityLittleMaidAvatar.func_71034_by(LMM_EntityLittleMaidAvatar.java:291)
	at littleMaidMobX.LMM_EntityAIAttackArrow.func_75246_d(LMM_EntityAIAttackArrow.java:191)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at littleMaidMobX.LMM_EntityLittleMaid.func_70619_bc(LMM_EntityLittleMaid.java:1582)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
	at littleMaidMobX.LMM_EntityLittleMaid.func_70636_d(LMM_EntityLittleMaid.java:1688)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at littleMaidMobX.LMM_EntityLittleMaid.func_70071_h_(LMM_EntityLittleMaid.java:1912)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.battlegear2.BowHookContainerClass2$OffhandQuiverSelection.getQuiverFor(BowHookContainerClass2.java:39)
	at mods.battlegear2.api.quiver.QuiverArrowRegistry.getArrowContainer(QuiverArrowRegistry.java:126)
	at mods.battlegear2.BowHookContainerClass2.onBowFiring(BowHookContainerClass2.java:118)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_BowHookContainerClass2_onBowFiring_ArrowLooseEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.item.ItemBow.func_77615_a(ItemBow.java:37)
	at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:402)
	at littleMaidMobX.LMM_SwingStatus.stopUsingItem(LMM_SwingStatus.java:170)
	at littleMaidMobX.LMM_EntityLittleMaidAvatar.stopUsingItem(LMM_EntityLittleMaidAvatar.java:283)
	at littleMaidMobX.LMM_EntityLittleMaidAvatar.func_71034_by(LMM_EntityLittleMaidAvatar.java:291)
	at littleMaidMobX.LMM_EntityAIAttackArrow.func_75246_d(LMM_EntityAIAttackArrow.java:191)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at littleMaidMobX.LMM_EntityLittleMaid.func_70619_bc(LMM_EntityLittleMaid.java:1582)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
	at littleMaidMobX.LMM_EntityLittleMaid.func_70636_d(LMM_EntityLittleMaid.java:1688)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at littleMaidMobX.LMM_EntityLittleMaid.func_70071_h_(LMM_EntityLittleMaid.java:1912)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: lmmx.LittleMaidX (littleMaidMobX.LMM_EntityLittleMaid)
	Entity ID: 228390
	Entity Name: Little Maid
	Entity's Exact location: -1276.64, 4.00, 2013.66
	Entity's Block location: World: (-1277,4,2013), Chunk: (at 3,0,13 in -80,125; contains blocks -1280,0,2000 to -1265,255,2015), Region: (-3,3; contains chunks -96,96 to -65,127, blocks -1536,0,1536 to -1025,255,2047)
	Entity's Momentum: -0.04, -0.08, 0.01
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['JoshB2001'/338, l='New World', x=-1272.97, y=4.00, z=2019.39]]
	Chunk stats: ServerChunkCache: 745 Drop: 0
	Level seed: -3354455742210136589
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-1284,4,1960), Chunk: (at 12,0,8 in -81,122; contains blocks -1296,0,1952 to -1281,255,1967), Region: (-3,3; contains chunks -96,96 to -65,127, blocks -1536,0,1536 to -1025,255,2047)
	Level time: 29543 game time, 29543 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 103327 (now: false), thunder time: 114800 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_75, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 570835432 bytes (544 MB) / 1623719936 bytes (1548 MB) up to 2863661056 bytes (2731 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 6 loaded mod(s)
          - VoxelPlayer version 0.12.0
          - VoxelMenu version 4.1.4
          - VoxelCam version 1.3.2
          - RenderDecorator version 1.1.1
          - VoxelLib version 2.3.1
          - VoxelMenu Music version 12.0
	LaunchWrapper: 51 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ModelBipedTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemRendererTransformer
          - Transformer: mods.battlegear2.coremod.transformers.MinecraftTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemStackTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemInWorldTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
          - Transformer: am2.preloader.BytecodeTransformers
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: mmmlibx.lib.multiModel.MMMLoader.MMMTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: mods.battlegear2.coremod.transformers.BattlegearAccessTransformer
          - Transformer: nf.fr.ephys.cookiecore.common.core.CookieCoreAT
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: Reika.DragonAPI.ASM.InterfaceInjector
          - Transformer: Reika.DragonAPI.ASM.APIStripper
          - Transformer: Reika.DragonAPI.ASM.DragonAPIClassTransfomer
          - Transformer: Reika.DragonAPI.ASM.FMLItemBlockPatch
          - Transformer: Reika.DragonAPI.ASM.DependentMethodStripper
          - Transformer: tterrag.core.common.transform.TTCoreTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.thevoxelbox.common.TimeUpdateTransformer
          - Transformer: com.thevoxelbox.voxelmenu.SlotTransformer
          - Transformer: com.thevoxelbox.voxelmenu.PanoramaTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.thatapplefreak.voxelcam.VoxelCamTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.renderdecorator.asm.RenderPlayerTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 53 mods loaded, 53 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OldModelLoader{1.0} [OldModelLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.12} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.2} [Treecapitator] ([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Aquaculture{1.2.3} [Aquaculture] (Aquaculture-1.7.10-1.2.5.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	atum{0.6} [Atum] (Atum-1.7.10-0.6.57.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cookiecore{1.3.0} [Cookie Core] (cookiecore-1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V6c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CritterPet{beta} [Critter Pet] (CritterPet 1.7.10 V6a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraFood{0.6.0} [Extra Food] (ExtraFood-1.7.10-0.6.47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	godweapons{2.5} [Gods' Weapons] (godweapons - 1.7.10 - 2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	iChunUtil{4.1.0} [iChunUtil] (iChunUtil-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lmmx{1.0} [lmmx] (littleMaidMobX-1.7.x_0.0.8pre3 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MMMLibX{1.7.x-srg-1} [MMMLibX] (littleMaidMobX-1.7.x_0.0.8pre3 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	zabuton{1.0} [zabuton] (littleMaidMobX-1.7.x_0.0.8pre3 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MobAmputation{4.0.0} [MobAmputation] (MobAmputation-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_Modchu_ModchuLib{179-10} [mod_Modchu_ModchuLib] (ModchuLib_1_7_10-v10f (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	recipehandler{0.2} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.2(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TSteelworks{1.7.10-1.0.7} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ttCore{MC1.7.10-0.1.0-67} [ttCore] (ttCore-MC1.7.10-0.1.0-67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2-client.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wailaplugins{MC1.7.10-0.0.1-13} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-13-client.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	zombiebearbalkons{0.1.0} [Balkon's/Metallurgy Compatability] (Zombiebear -Compatability for Balkons-1.7.10 - 0.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IguanaTweaksTConstruct{1.7.10-2.1.4.132} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['JoshB2001'/338, l='New World', x=-1272.97, y=4.00, z=2019.39]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Alexander175** [comment]
I noticed this was already reported sorry.
