### ISSUE TITLE
hey i am again after older issues i find a new bug with battle gear2 this is a crash report

### ISSUE THREAD

**Issue by zingza555** [KuroNeko87/littleMaidMobX#18]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 30/4/2558, 17:37 น.
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at person.mister.auw.GuiModifySlot.drawGuiContainerBackgroundLayer(GuiModifySlot.java:1314)
	at person.mister.auw.GuiModifySlot.func_73863_a(GuiModifySlot.java:1354)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)
	at noppes.mpm.client.EntityRendererAlt.func_78480_b(EntityRendererAlt.java:34)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at person.mister.auw.GuiModifySlot.drawGuiContainerBackgroundLayer(GuiModifySlot.java:1314)
	at person.mister.auw.GuiModifySlot.func_73863_a(GuiModifySlot.java:1354)

-- Screen render details --
Details:
	Screen name: ~~NULL~~
	Mouse location: Scaled: (258, 247). Absolute: (516, 273)
	Screen size: Scaled: (683, 384). Absolute: (1366, 768). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['zingza555'/70, l='MpServer', x=-719.39, y=5.62, z=-416.06]]
	Chunk stats: MultiplayerChunkCache: 121, 130
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-741,4,-383), Chunk: (at 11,0,1 in -47,-24; contains blocks -752,0,-384 to -737,255,-369), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 15630 game time, 15630 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 73 total; [EntitySlime['Slime'/11014, l='MpServer', x=-715.08, y=4.00, z=-489.16], EntityZombie['Zombie'/6663, l='MpServer', x=-668.69, y=5.00, z=-449.50], EntitySlime['Slime'/9360, l='MpServer', x=-757.76, y=4.00, z=-486.49], EntityItem['item.item.egg'/7955, l='MpServer', x=-734.66, y=4.13, z=-353.16], EntityItem['item.item.seeds'/10131, l='MpServer', x=-659.09, y=5.13, z=-436.56], EntityBat['Bat'/11035, l='MpServer', x=-703.41, y=4.00, z=-472.84], EntityBat['Bat'/11036, l='MpServer', x=-692.81, y=6.10, z=-449.50], EntityCreeper['Creeper'/10399, l='MpServer', x=-785.50, y=4.00, z=-390.50], EntityBat['Bat'/11041, l='MpServer', x=-693.25, y=6.67, z=-448.25], EntityBat['Bat'/10914, l='MpServer', x=-668.04, y=4.99, z=-421.26], EntityVillager['Villager'/35, l='MpServer', x=-687.05, y=4.00, z=-473.18], EntityVillager['Villager'/36, l='MpServer', x=-662.50, y=4.00, z=-457.50], EntityVillager['Villager'/37, l='MpServer', x=-660.64, y=4.00, z=-457.23], EntityVillager['Villager'/38, l='MpServer', x=-686.76, y=4.00, z=-480.86], EntityZombie['Zombie'/10406, l='MpServer', x=-775.50, y=4.00, z=-490.50], EntityVillager['Villager'/39, l='MpServer', x=-698.44, y=5.00, z=-462.56], EntityVillager['Villager'/40, l='MpServer', x=-681.69, y=5.00, z=-463.16], EntityBat['Bat'/11176, l='MpServer', x=-680.96, y=5.00, z=-464.27], EntityVillager['Villager'/41, l='MpServer', x=-657.72, y=4.00, z=-454.47], EntityVillager['Villager'/42, l='MpServer', x=-673.78, y=5.00, z=-484.83], EntitySlime['Slime'/170, l='MpServer', x=-654.83, y=5.10, z=-449.80], EntityVillager['Villager'/43, l='MpServer', x=-676.02, y=5.00, z=-484.33], EntityVillager['Villager'/44, l='MpServer', x=-684.41, y=5.00, z=-476.94], EntityVillager['Villager'/46, l='MpServer', x=-681.69, y=5.00, z=-464.69], EntityVillager['Villager'/47, l='MpServer', x=-680.47, y=5.00, z=-463.97], EntitySlime['Slime'/7856, l='MpServer', x=-676.22, y=4.33, z=-430.22], EntityVillager['Villager'/48, l='MpServer', x=-649.50, y=5.00, z=-453.31], EntitySlime['Slime'/305, l='MpServer', x=-700.22, y=4.50, z=-459.31], EntityVillager['Villager'/49, l='MpServer', x=-653.65, y=5.00, z=-456.53], EntityVillager['Villager'/50, l='MpServer', x=-669.16, y=4.00, z=-464.97], EntityZombie['Zombie'/11058, l='MpServer', x=-664.50, y=15.47, z=-453.45], EntitySkeleton['Skeleton'/10418, l='MpServer', x=-734.50, y=4.00, z=-448.50], EntityZombie['Zombie'/11059, l='MpServer', x=-767.59, y=4.00, z=-450.06], EntityVillager['Villager'/51, l='MpServer', x=-657.44, y=5.00, z=-462.47], EntityVillager['Villager'/52, l='MpServer', x=-664.56, y=5.00, z=-450.34], EntityZombie['Zombie'/11060, l='MpServer', x=-656.50, y=4.00, z=-401.50], EntityVillager['Villager'/53, l='MpServer', x=-671.66, y=5.00, z=-449.91], EntityItem['item.item.egg'/9397, l='MpServer', x=-731.31, y=4.13, z=-355.03], EntityBat['Bat'/11189, l='MpServer', x=-691.75, y=8.10, z=-417.44], EntityCreeper['Creeper'/11062, l='MpServer', x=-741.38, y=4.00, z=-346.97], EntitySkeleton['Skeleton'/11063, l='MpServer', x=-733.50, y=4.00, z=-449.50], EntitySkeleton['Skeleton'/11064, l='MpServer', x=-748.13, y=4.00, z=-445.66], EntityVillager['Villager'/56, l='MpServer', x=-648.50, y=5.00, z=-463.50], EntitySkeleton['Skeleton'/11065, l='MpServer', x=-739.50, y=4.00, z=-452.50], EntityChicken['Chicken'/185, l='MpServer', x=-659.50, y=4.00, z=-406.50], EntityVillager['Villager'/57, l='MpServer', x=-654.69, y=5.00, z=-455.98], EntityChicken['Chicken'/186, l='MpServer', x=-660.50, y=4.00, z=-404.50], EntityVillager['Villager'/58, l='MpServer', x=-648.09, y=5.00, z=-462.56], EntityChicken['Chicken'/187, l='MpServer', x=-661.50, y=4.00, z=-405.50], EntityVillager['Villager'/59, l='MpServer', x=-665.08, y=5.00, z=-456.68], EntitySkeleton['Skeleton'/11068, l='MpServer', x=-776.50, y=4.00, z=-358.50], EntityChicken['Chicken'/188, l='MpServer', x=-661.50, y=4.00, z=-409.50], EntitySkeleton['Skeleton'/11069, l='MpServer', x=-776.50, y=4.00, z=-359.50], EntitySkeleton['Skeleton'/11070, l='MpServer', x=-773.50, y=4.00, z=-360.50], EntitySlime['Slime'/7871, l='MpServer', x=-692.94, y=5.00, z=-430.31], EntityCreeper['Creeper'/11072, l='MpServer', x=-729.13, y=4.00, z=-361.16], EntityZombie['Zombie'/9409, l='MpServer', x=-764.22, y=4.00, z=-453.25], EntitySheep['Sheep'/197, l='MpServer', x=-734.03, y=4.00, z=-451.09], EntitySlime['Slime'/8518, l='MpServer', x=-699.63, y=4.00, z=-451.38], EntityClientPlayerMP['zingza555'/70, l='MpServer', x=-719.39, y=5.62, z=-416.06], EntityCreeper['Creeper'/11080, l='MpServer', x=-725.50, y=4.00, z=-351.50], EntityChicken['Chicken'/201, l='MpServer', x=-733.81, y=4.00, z=-352.59], EntitySkeleton['Skeleton'/11081, l='MpServer', x=-688.53, y=4.00, z=-477.38], EntityChicken['Chicken'/202, l='MpServer', x=-732.13, y=4.00, z=-355.75], EntityChicken['Chicken'/203, l='MpServer', x=-734.75, y=4.00, z=-354.03], EntityChicken['Chicken'/204, l='MpServer', x=-738.84, y=4.00, z=-347.91], EntitySlime['Slime'/9168, l='MpServer', x=-734.58, y=4.62, z=-369.43], EntitySlime['Slime'/4192, l='MpServer', x=-657.60, y=4.00, z=-447.62], EntityBat['Bat'/11108, l='MpServer', x=-673.44, y=5.00, z=-433.75], EntityBat['Bat'/9445, l='MpServer', x=-673.25, y=5.00, z=-492.50], EntityBat['Bat'/10989, l='MpServer', x=-684.41, y=6.73, z=-468.09], EntityBat['Bat'/9454, l='MpServer', x=-699.33, y=5.39, z=-460.50], EntitySlime['Slime'/117, l='MpServer', x=-673.88, y=4.93, z=-441.78]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 120509184 bytes (114 MB) / 338001920 bytes (322 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.130.1395 Minecraft Forge 10.13.3.1395 Optifine OptiFine_1.7.10_HD_B7 15 mods loaded, 15 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{7.10.130.1395} [Forge Mod Loader] (forge-1.7.10-10.13.3.1395-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{10.13.3.1395} [Minecraft Forge] (forge-1.7.10-10.13.3.1395-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	alluwant{2.1} [All U Want] (All-U-Want 2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	armourersWorkshop{1.7.10-0.31.2.82} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.31.2.82.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	custom_sword{1.7.2} [Custom Sword  By Kelco_K22] (custom_sword_1.7.2_V0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	me{1.3.2.1} [More Enchantments] (MoreEnchantments-1.7.10-1.3.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AencEx{0.0.1} [AencEx] (MoreEnchantments-1.7.10-1.3.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	MoreEnchants{1.3.0} [MoreEnchants] (MoreEnchants-MC1.7-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	MSM3{3.0.0d} [More Swords 3] (MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	poisonedarrows{0.0.0} [Poisoned Arrows Mod] (poisonedarrows0108827484.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	SmartCursor{1.4.0} [SmartCursor] (SmartCursor-1.4.0-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.2843' Renderer: 'Intel(R) HD Graphics 3000'
	Launched Version: 1.7.10-Forge10.13.3.1395-1710ls
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.2843, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Mrbysco** [comment]
This is still because of Littlemaidmob and Battlegear 2 aren't compatable #11
